//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference2
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TablaMultiplicar", Namespace="http://schemas.datacontract.org/2004/07/LogicServiceMatematicas")]
    public partial class TablaMultiplicar : object
    {
        
        private string OperacionField;
        
        private int ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operacion
        {
            get
            {
                return this.OperacionField;
            }
            set
            {
                this.OperacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference2.IServiceTablaMultiplicar")]
    public interface IServiceTablaMultiplicar
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTablaMultiplicar/GetTablaMultiplicar", ReplyAction="http://tempuri.org/IServiceTablaMultiplicar/GetTablaMultiplicarResponse")]
        System.Threading.Tasks.Task<ServiceReference2.TablaMultiplicar[]> GetTablaMultiplicarAsync(int numero);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface IServiceTablaMultiplicarChannel : ServiceReference2.IServiceTablaMultiplicar, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class ServiceTablaMultiplicarClient : System.ServiceModel.ClientBase<ServiceReference2.IServiceTablaMultiplicar>, ServiceReference2.IServiceTablaMultiplicar
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceTablaMultiplicarClient() : 
                base(ServiceTablaMultiplicarClient.GetDefaultBinding(), ServiceTablaMultiplicarClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceTablaMultiplicar.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceTablaMultiplicarClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceTablaMultiplicarClient.GetBindingForEndpoint(endpointConfiguration), ServiceTablaMultiplicarClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceTablaMultiplicarClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceTablaMultiplicarClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceTablaMultiplicarClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceTablaMultiplicarClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceTablaMultiplicarClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference2.TablaMultiplicar[]> GetTablaMultiplicarAsync(int numero)
        {
            return base.Channel.GetTablaMultiplicarAsync(numero);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceTablaMultiplicar))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceTablaMultiplicar))
            {
                return new System.ServiceModel.EndpointAddress("http://hostservicenumerodoblepgs.azurewebsites.net/ServiceTablaMultiplicar.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceTablaMultiplicarClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceTablaMultiplicar);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceTablaMultiplicarClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceTablaMultiplicar);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceTablaMultiplicar,
        }
    }
}
